# Generated by Django 3.1.3 on 2020-12-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201231_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='Product_Name',
            field=models.ManyToManyField(blank=True, related_name='likes', to='auctions.Auction'),
        ),
    ]
