# Generated by Django 3.1.3 on 2021-01-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='Product_Name',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='Product_Name',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='auctions.auction'),
            preserve_default=False,
        ),
    ]
