# Generated by Django 3.1.3 on 2021-01-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210101_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='listing_status',
            field=models.CharField(choices=[('ac', 'Active'), ('cl', 'Closed')], default='ac', max_length=2),
        ),
    ]
