# Generated by Django 3.1.3 on 2021-01-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='Product_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_bids', to='auctions.auction'),
        ),
    ]
