# Generated by Django 3.1.3 on 2021-01-13 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210103_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
    ]
