# Generated by Django 3.1.3 on 2021-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product_cat',
            field=models.CharField(choices=[('AA', 'Apparel and Accessories'), ('SF', 'Style and Fashion'), ('HG', 'Home and Garden'), ('SG', 'Sporting and Goods'), ('HW', 'Health and Wellness'), ('CI', 'Children and Infants'), ('EG', 'Electronic Goods'), ('HO', 'Home'), ('AU', 'Automotive'), ('OC', 'Other Categories'), ('NK', 'Not Known')], default='NK', max_length=2),
        ),
    ]
